version: '3.0'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - texhno
networks:
  texhno:
